//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamClient.StreamServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StreamServiceReference.IStreamService")]
    public interface IStreamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetStream", ReplyAction="http://tempuri.org/IStreamService/GetStreamResponse")]
        System.IO.Stream GetStream(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetStream", ReplyAction="http://tempuri.org/IStreamService/GetStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetStreamAsync(string name);
        
        // CODEGEN: Generating message contract since the wrapper name (RequestFileMessage) of message RequestFileMessage does not match the default value (GetRfmStream)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetRfmStream", ReplyAction="http://tempuri.org/IStreamService/GetRfmStreamResponse")]
        StreamClient.StreamServiceReference.ResponseFileMessage GetRfmStream(StreamClient.StreamServiceReference.RequestFileMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStreamService/GetRfmStream", ReplyAction="http://tempuri.org/IStreamService/GetRfmStreamResponse")]
        System.Threading.Tasks.Task<StreamClient.StreamServiceReference.ResponseFileMessage> GetRfmStreamAsync(StreamClient.StreamServiceReference.RequestFileMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestFileMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestFileMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public RequestFileMessage() {
        }
        
        public RequestFileMessage(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResponseFileMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResponseFileMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string name;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream data;
        
        public ResponseFileMessage() {
        }
        
        public ResponseFileMessage(string name, long size, System.IO.Stream data) {
            this.name = name;
            this.size = size;
            this.data = data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamServiceChannel : StreamClient.StreamServiceReference.IStreamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamServiceClient : System.ServiceModel.ClientBase<StreamClient.StreamServiceReference.IStreamService>, StreamClient.StreamServiceReference.IStreamService {
        
        public StreamServiceClient() {
        }
        
        public StreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetStream(string name) {
            return base.Channel.GetStream(name);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetStreamAsync(string name) {
            return base.Channel.GetStreamAsync(name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamClient.StreamServiceReference.ResponseFileMessage StreamClient.StreamServiceReference.IStreamService.GetRfmStream(StreamClient.StreamServiceReference.RequestFileMessage request) {
            return base.Channel.GetRfmStream(request);
        }
        
        public long GetRfmStream(ref string name, out System.IO.Stream data) {
            StreamClient.StreamServiceReference.RequestFileMessage inValue = new StreamClient.StreamServiceReference.RequestFileMessage();
            inValue.name = name;
            StreamClient.StreamServiceReference.ResponseFileMessage retVal = ((StreamClient.StreamServiceReference.IStreamService)(this)).GetRfmStream(inValue);
            name = retVal.name;
            data = retVal.data;
            return retVal.size;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamClient.StreamServiceReference.ResponseFileMessage> StreamClient.StreamServiceReference.IStreamService.GetRfmStreamAsync(StreamClient.StreamServiceReference.RequestFileMessage request) {
            return base.Channel.GetRfmStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamClient.StreamServiceReference.ResponseFileMessage> GetRfmStreamAsync(string name) {
            StreamClient.StreamServiceReference.RequestFileMessage inValue = new StreamClient.StreamServiceReference.RequestFileMessage();
            inValue.name = name;
            return ((StreamClient.StreamServiceReference.IStreamService)(this)).GetRfmStreamAsync(inValue);
        }
    }
}
